# Generated by Django 4.1.7 on 2023-04-19 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promptbook', '0013_category_pinned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, default=False, related_name='pinned_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
