# Generated by Django 4.1.7 on 2023-04-20 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promptbook', '0014_alter_category_pinned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promptbook.category'),
        ),
        migrations.AlterField(
            model_name='promptlabel',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promptbook.label'),
        ),
    ]
